Repository kubernetes-sigs/aws-fsx-csi-driver, pull requests merged in 2019-12, with the labels that each got.

#118 Use main from e2e tester
  Makefile
  go.mod
  go.sum
  tester/cmd/main.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, size/M

#121 Scope down recommended IAM policy
  docs/README.md
  tester/e2e-test-config.yaml
Labels: approved, cncf-cla: yes, size/S

#122 Switch to use kustomize
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/csidriver.yaml
  deploy/kubernetes/base/kustomization.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/base/rbac.yaml
  deploy/kubernetes/manifest.yaml
  deploy/kubernetes/overlays/dev/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
  examples/kubernetes/dynamic_provisioning/specs/storageclass.yaml
  tester/e2e-test-config.yaml
Labels: approved, cncf-cla: yes, size/L

#123 Add iam:CreateServiceLinkedRole for fsx.amazonaws.com service
  docs/README.md
Labels: approved, cncf-cla: yes, size/S

#119 Fix paths to dynamic_provisioning_s3 manifests
  examples/kubernetes/dynamic_provisioning_s3/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#111 Add conformance tests
  go.mod
  go.sum
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/cloud/metadata.go
  pkg/driver/driver.go
  pkg/driver/fakes.go
  pkg/driver/mocks/mock_cloud.go
  pkg/driver/mocks/mock_mount.go
  pkg/driver/mount.go
  tester/e2e-test-config.yaml
  tests/e2e/cloud.go
  tests/e2e/conformance_test.go
  tests/e2e/suite_test.go
  tests/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, size/XL
