Repository kubernetes-sigs/aws-fsx-csi-driver, pull requests merged in 2019-08, with the labels that each got.

#69 Update to CSI v1.1.0
  go.mod
  go.sum
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/driver.go
  pkg/driver/identity.go
  pkg/driver/node.go
  pkg/driver/node_test.go
  tests/sanity/sanity_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#76 Update README
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#74 Implement mount options support
  docs/README.md
  examples/kubernetes/dynamic_provisioning/specs/storageclass.yaml
  examples/kubernetes/dynamic_provisioning_s3/specs/storageclass.yaml
  examples/kubernetes/multiple_pods/specs/storageclass.yaml
  examples/kubernetes/static_provisioning/specs/storageclass.yaml
  pkg/driver/node.go
  pkg/driver/node_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#75 Clean up deploy manifest for 1.14
  Makefile
  deploy/kubernetes/manifest.yaml
  pkg/driver/node_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#82 Fix manifest csi driver object
  deploy/kubernetes/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#84 Remove DISCLAIMER
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#87 Bump golang version to 1.12.7
  .travis.yml
  Dockerfile
  docs/README.md
Labels: approved, cncf-cla: yes, size/XS

#86 Bump driver version to 0.2.0
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#89 Add dockerignore to ignore vendor dir
  .dockerignore
Labels: approved, cncf-cla: yes, size/XS
