Repository kubernetes-sigs/aws-fsx-csi-driver, pull requests merged in 2020-02, with the labels that each got.

#131 Update aws sdk for new fsx API and run go mod tidy
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#130 Add support for FSx for lustre create API deployment type
  examples/kubernetes/dynamic_provisioning/README.md
  examples/kubernetes/dynamic_provisioning/specs/storageclass.yaml
  examples/kubernetes/dynamic_provisioning_s3/README.md
  examples/kubernetes/dynamic_provisioning_s3/specs/storageclass.yaml
  examples/kubernetes/max_cache_tuning/specs/storageclass.yaml
  examples/kubernetes/multiple_pods/README.md
  examples/kubernetes/multiple_pods/specs/storageclass.yaml
  examples/kubernetes/static_provisioning/README.md
  examples/kubernetes/static_provisioning/specs/pv.yaml
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/cloud/fakes.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/node.go
  pkg/driver/node_test.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#134 Update v0.3.0 documentation
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#135 Post release doc update
  CHANGELOG-0.x.md
  Makefile
Labels: approved, cncf-cla: yes, size/XS
