Repository kubernetes-sigs/aws-fsx-csi-driver, pull requests merged in 2020-03, with the labels that each got.

#136 Fix e2e test
  tester/e2e-test-config.yaml
Labels: approved, cncf-cla: yes, size/XS

#132 Add Helm chart deployment
  .gitignore
  deploy/kubernetes/helm/.helmignore
  deploy/kubernetes/helm/Chart.yaml
  deploy/kubernetes/helm/README.md
  deploy/kubernetes/helm/templates/_helpers.tpl
  deploy/kubernetes/helm/templates/controller.yaml
  deploy/kubernetes/helm/templates/csidriver.yaml
  deploy/kubernetes/helm/templates/node.yaml
  deploy/kubernetes/helm/templates/serviceaccount.yaml
  deploy/kubernetes/helm/values.yaml
  tester/e2e-test-config.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#139 [Trival] replace beta label to GA label for kubernetes
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/helm/README.md
  deploy/kubernetes/helm/values.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#138 Issue #137, adding Pod Affinity to target architecture
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
