Repository kubernetes-sigs/aws-fsx-csi-driver, pull requests merged in 2021-12, with the labels that each got.

#227 Release 0.7.1 part 1/3: CHANGELOG, README, Makefile
  CHANGELOG-0.x.md
  Makefile
  docs/README.md
Labels: ok-to-test, approved, size/XS, cncf-cla: yes, lgtm

#228 Add make all-push rule
  .github/workflows/container-image.yaml
  Dockerfile
  Makefile
Labels: approved, size/L, cncf-cla: yes, lgtm

#229 Release 0.7.1 part 2/3: helm and kustomize
  charts/aws-fsx-csi-driver/CHANGELOG.md
  charts/aws-fsx-csi-driver/Chart.yaml
  charts/aws-fsx-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/controller-serviceaccount.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, cncf-cla: yes, size/M, lgtm

#230 Release 0.7.1 part 3/3
  CHANGELOG-0.x.md
  charts/aws-fsx-csi-driver/CHANGELOG.md
  charts/aws-fsx-csi-driver/Chart.yaml
  charts/aws-fsx-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/controller-serviceaccount.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
Labels: approved, cncf-cla: yes, size/M, lgtm

#231 Update ECR sidecars to 1-18-13
  charts/aws-fsx-csi-driver/CHANGELOG.md
  charts/aws-fsx-csi-driver/Chart.yaml
  charts/aws-fsx-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
Labels: approved, size/S, cncf-cla: yes, lgtm

#234 Release 0.8.0 part 1/3: CHANGELOG, README, Makefile
  CHANGELOG-0.x.md
  Makefile
  docs/README.md
Labels: cncf-cla: no, ok-to-test, approved, size/S, cncf-cla: yes, lgtm

#236 Release 0.8.0 part 3/3
  CHANGELOG-0.x.md
  Makefile
  charts/aws-fsx-csi-driver/CHANGELOG.md
  charts/aws-fsx-csi-driver/Chart.yaml
  charts/aws-fsx-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
Labels: approved, cncf-cla: yes, size/M, lgtm

#235 Release 0.8.0 part 2/3: helm and kustomize
  charts/aws-fsx-csi-driver/CHANGELOG.md
  charts/aws-fsx-csi-driver/Chart.yaml
  charts/aws-fsx-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, size/S, cncf-cla: yes, lgtm
