Repository kubernetes-sigs/aws-fsx-csi-driver, pull requests merged in 2021-11, with the labels that each got.

#216 Release 0.6.0 part 3/3: merge previous parts to master
  CHANGELOG-0.x.md
  Makefile
  charts/aws-fsx-csi-driver/CHANGELOG.md
  charts/aws-fsx-csi-driver/Chart.yaml
  charts/aws-fsx-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
Labels: approved, cncf-cla: yes, size/M, lgtm

#215 Update Doc and Support Template
  .github/ISSUE_TEMPLATE/support-request.md
  docs/README.md
Labels: ok-to-test, approved, size/XS, cncf-cla: yes, lgtm

#217 Add ARM support
  .github/workflows/container-image.yaml
  Dockerfile
  Makefile
Labels: ok-to-test, approved, cncf-cla: yes, size/M, lgtm

#219 Release 0.7.0 part 1/3: CHANGELOG, README, Makefile
  CHANGELOG-0.x.md
  Makefile
  docs/README.md
Labels: ok-to-test, approved, size/S, cncf-cla: yes, lgtm

#221 Use latest buildx github action and build target platform from build platform
  .github/workflows/container-image.yaml
  Dockerfile
  Makefile
  hack/e2e/README.md
  hack/e2e/ecr.sh
  hack/e2e/eksctl.sh
  hack/e2e/run.sh
Labels: approved, size/L, cncf-cla: yes, lgtm

#223 Release 0.7.0 part 2/3: helm and kustomize
  CHANGELOG-0.x.md
  charts/aws-fsx-csi-driver/CHANGELOG.md
  charts/aws-fsx-csi-driver/Chart.yaml
  charts/aws-fsx-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: ok-to-test, approved, size/S, cncf-cla: yes, lgtm

#224 Release 0.7.0 part 3/3
  CHANGELOG-0.x.md
  charts/aws-fsx-csi-driver/CHANGELOG.md
  charts/aws-fsx-csi-driver/Chart.yaml
  charts/aws-fsx-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
Labels: ok-to-test, approved, cncf-cla: yes, size/M, lgtm
