Repository kubernetes-sigs/aws-fsx-csi-driver, pull requests merged in 2021-06, with the labels that each got.

#166 Post-release v0.4.0
  CHANGELOG-0.x.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#173 Add self to OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#186 Add support for Lustre compression
  examples/kubernetes/dynamic_provisioning/README.md
  examples/kubernetes/dynamic_provisioning/specs/storageclass.yaml
  go.mod
  go.sum
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#177 Update README for stable release
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#188 Updated helm chart dns config and imagePullSecrets
  charts/aws-fsx-csi-driver/Chart.yaml
  charts/aws-fsx-csi-driver/templates/controller.yaml
  charts/aws-fsx-csi-driver/templates/node.yaml
  charts/aws-fsx-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M
