Repository kubernetes-sigs/aws-fsx-csi-driver, pull requests merged in 2022-10, with the labels that each got.

#262 Added templating for CSIDriver object configuration
  charts/aws-fsx-csi-driver/CHANGELOG.md
  charts/aws-fsx-csi-driver/Chart.yaml
  charts/aws-fsx-csi-driver/templates/csidriver.yaml
  charts/aws-fsx-csi-driver/values.yaml
Labels: ok-to-test, approved, size/S, cncf-cla: yes, lgtm

#264 Release 0.8.3 part 2/3: helm and kustomize update
  charts/aws-fsx-csi-driver/CHANGELOG.md
  charts/aws-fsx-csi-driver/Chart.yaml
  charts/aws-fsx-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: ok-to-test, approved, size/S, cncf-cla: yes, lgtm

#266 Release 0.8.3 part 3/3: Merge to master
  charts/aws-fsx-csi-driver/CHANGELOG.md
  charts/aws-fsx-csi-driver/Chart.yaml
  charts/aws-fsx-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, size/S, needs-ok-to-test, cncf-cla: yes, lgtm

#267 Bump klog to klog2
  cmd/main.go
  go.mod
  pkg/cloud/cloud.go
  pkg/driver/controller.go
  pkg/driver/driver.go
  pkg/driver/node.go
  vendor/modules.txt
Labels: approved, size/S, cncf-cla: yes, lgtm

#270 Release 0.8.3 part 2/3: helm and kustomize update correction
  charts/aws-fsx-csi-driver/CHANGELOG.md
  charts/aws-fsx-csi-driver/Chart.yaml
Labels: ok-to-test, approved, size/XS, cncf-cla: yes, lgtm

#271 Release 0.8.3 part 2/3: helm and kustomize update correction
  charts/aws-fsx-csi-driver/CHANGELOG.md
  charts/aws-fsx-csi-driver/Chart.yaml
Labels: ok-to-test, approved, size/S, cncf-cla: yes, lgtm
