Repository kubernetes-sigs/aws-fsx-csi-driver, pull requests merged in 2025-08, with the labels that each got.

#445 Release 1.5.0 1/3: Update docs and version
  CHANGELOG-0.x.md
  Makefile
  docs/README.md
  docs/install.md
Labels: ok-to-test, approved, size/S, cncf-cla: yes, lgtm

#447 Fix: Add AL_VERSION default value in Makefile
  Makefile
Labels: ok-to-test, approved, size/XS, cncf-cla: yes, lgtm

#449 Release 1.5.0 1/3: Update docs and version
  CHANGELOG-0.x.md
  Makefile
  docs/README.md
  docs/install.md
Labels: ok-to-test, approved, size/S, cncf-cla: yes, lgtm

#451 Release 1.5 3/3 - Merge release-1.5 to master
  CHANGELOG-0.x.md
  Makefile
  charts/aws-fsx-csi-driver/CHANGELOG.md
  charts/aws-fsx-csi-driver/Chart.yaml
  charts/aws-fsx-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  docs/README.md
  docs/install.md
Labels: approved, cncf-cla: yes, size/M, lgtm

#454 Add podLabels parameter Original work by bueti in PR 416 and Allow timeout to be set Original work by coolstim in PR 435
  charts/aws-fsx-csi-driver/templates/controller-deployment.yaml
  charts/aws-fsx-csi-driver/templates/node-daemonset.yaml
  charts/aws-fsx-csi-driver/values.yaml
Labels: ok-to-test, approved, size/S, cncf-cla: yes, lgtm
