Repository kubernetes-sigs/aws-fsx-csi-driver, pull requests merged in 2025-05, with the labels that each got.

#418 Bump sidecar images for v1.4.0
  charts/aws-fsx-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
Labels: approved, size/S, cncf-cla: yes, lgtm

#421 Release 1.4.0 part 1/3
  CHANGELOG-0.x.md
  Makefile
  docs/README.md
  docs/install.md
Labels: approved, size/S, cncf-cla: yes, lgtm

#422 Update provenance check for changed message
  hack/provenance
Labels: approved, size/XS, cncf-cla: yes, lgtm

#419 add documentation for Auto Mode specific settings
  docs/install.md
Labels: approved, cncf-cla: yes, size/M, lgtm

#424 Release 1.4.0 part 1/3
  CHANGELOG-0.x.md
  Makefile
  docs/README.md
  docs/install.md
Labels: approved, size/S, cncf-cla: yes, lgtm

#425 Release 1.4.0 part 1/3
  CHANGELOG-0.x.md
  Makefile
  docs/README.md
  docs/install.md
Labels: approved, size/S, cncf-cla: yes, lgtm

#426 Release 1.4.0 2/3: helm and kustomize
  charts/aws-fsx-csi-driver/CHANGELOG.md
  charts/aws-fsx-csi-driver/Chart.yaml
  charts/aws-fsx-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
Labels: approved, size/S, cncf-cla: yes, lgtm
