Repository kubernetes-sigs/aws-fsx-csi-driver, pull requests merged in 2025-01, with the labels that each got.

#402 Add dynamic provisioning support for metadata configuration and efa
  examples/kubernetes/dynamic_provisioning/README.md
  go.mod
  go.sum
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
Labels: ok-to-test, approved, size/L, cncf-cla: yes, lgtm

#403 Bump dependencies for v1.3.0
  Dockerfile
  docs/README.md
  go.mod
  go.sum
  pkg/driver/controller.go
  pkg/driver/driver.go
  pkg/driver/mocks/mock_k8s_client.go
  pkg/driver/node.go
  pkg/driver/node_test.go
Labels: ok-to-test, approved, size/XL, cncf-cla: yes, lgtm

#405 Bump sidecar images for v1.3.0
  charts/aws-fsx-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
Labels: ok-to-test, approved, size/S, cncf-cla: yes, lgtm

#404 Sanitize CSI request logs
  pkg/driver/controller.go
  pkg/driver/node.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: ok-to-test, approved, cncf-cla: yes, size/M, lgtm

#406 Release 1.3.0 part 1/3
  CHANGELOG-0.x.md
  Makefile
  docs/README.md
  docs/install.md
Labels: ok-to-test, approved, size/S, cncf-cla: yes, lgtm

#407 Release 1.3.0 part 2: helm and kustomize
  charts/aws-fsx-csi-driver/CHANGELOG.md
  charts/aws-fsx-csi-driver/Chart.yaml
  charts/aws-fsx-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
Labels: ok-to-test, approved, size/S, cncf-cla: yes, lgtm

#408 Release 1.3 part 3/3
  CHANGELOG-0.x.md
  Makefile
  charts/aws-fsx-csi-driver/CHANGELOG.md
  charts/aws-fsx-csi-driver/Chart.yaml
  charts/aws-fsx-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  docs/README.md
  docs/install.md
Labels: approved, cncf-cla: yes, size/M, lgtm

#409 Handle empty and misconfigured extraTags in controller
  pkg/driver/controller.go
  pkg/driver/controller_test.go
Labels: approved, size/L, cncf-cla: yes, lgtm
